// This file is auto-generated by generate-config.py. Do not edit manually.

const SITE_CONFIG = {
  title: "Sumitpo",
  subtitle: "Programmer",
  description: "A knowledge base inspired by okmij.org/ftp/",
  githubUrl: "https://github.com/sumitpo/sumitpo.github.io",
  copyrightYear: "2025",
  postsDir: "posts/",
  postFiles: [
    "collects.html",
    "computer-graphic.html",
    "cxx-template.html",
    "markov-algorithms.html",
    "misc.html",
    "python-template.html"
  ]
};
